tools:
# version control
  git-filter-repo:
    brew: true
  git-lfs:
    brew: true
  gh:
    brew: true
  gitkraken:
    optional: true
    brew:
      cask: true
# repo utils
  pre-commit:
    brew: true
# runtimes
  # gnu extension language
  guile:
    optional: true
    brew: true
  tcl-tk:
    optional: true
    brew:
      link: false
  gradle-completion:
    optional: true
    brew: true
  rust:
    optional: true
    brew: true
  android-platform-tools:
    optional: true
    brew: true
# cli utils
  jwt-cli:
    optional: true
    brew:
      tap: mike-engel/jwt-cli
      name: mike-engel/jwt-cli/jwt-cli
  # command output timestamper
  ets:
    optional: true
    brew:
      tap: zmwangx/ets
      tapUrl: https://github.com/zmwangx/ets
      name: zmwangx/ets/ets
# markdown
  mdcat:
    brew: true
# networking
  telnet:
    brew: true
  nmap:
    brew: true
  zenmap:
    optional: true
    brew: true
  wireshark:
    optional: true
    brew: true
  wireshark-gui:
    optional: true
    brew:
      cask: true
  wireshark-chmodbpf:
    optional: true
    brew:
      cask: true
  httpie:
    brew: true
# IDEs
  visual-studio-code:
    optional: true
    brew:
      cask: true
