installToolDeps: true
tools:
  cask:
    brew: {}
# version control
  git:
    brew: {}
  # subversion:
  #   brew: {}
# shell
  bash:
    brew: {}
  bash-completion:
    optional: true
    checkBrew: true
    brew: {}
  coreutils:
    checkBrew: true
    brew: {}
  zsh:
    brew: {}
  zsh-completions:
    optional: true
    checkBrew: true
    brew: {}
  zinit:
    checkPath: zinit.zsh
    git:
      url: https://github.com/zdharma-continuum/zinit.git
      target: localshare/zinit/zinit.git
  menlo-font:
    artifact:
      url: https://github.com/ryanoasis/nerd-fonts/raw/v3.0.0/patched-fonts/Meslo/S/Regular/MesloLGSNerdFontMono-Regular.ttf
      target: ~/Library/Fonts
      appendFilename: true
  chezmoi:
    brew: {}
# runtime deps
  # gcc:
  #   brew: {}
  # glib:
  #   brew: {}
  # gobject-introspection:
  #   brew: {}
  # libxml2:
  #   brew: {}
  # libxmlsec1:
  #   brew: {}
  # readline:
  #   brew: {}
  # sqlite3:
  #   brew: {}
  # zlib:
  #   brew: {}
  # tcl-tk:
  #   brew: {}
  # https://nghttp2.org/
  # nghttp2:
  #   brew: {}
# media
  # webp:
  #   brew: {}
  # jpeg-xl:
  #   brew: {}
  # libavif:
  #   brew: {}
  # aom:
  #   brew: {}
  # gd:
  #   brew: {}
  # gdk-pixbuf:
  #   brew: {}
  # netpbm:
  #   brew: {}
# fonts
  # fontconfig:
  #   brew: {}
  # harfbuzz:
  #   brew: {}
  # pango:
  #   brew: {}
# svg
  # cairo:
  #   brew: {}
  # librsvg:
  #   brew: {}
# viz
  graphviz:
    optional: true
    brew: {}
# crypto
  gnupg:
    checkCommand: gpg
    brew: {}
  # gnutls:
  #   brew: {}
  # krb5:
  #   brew: {}
  # libssh:
  #   brew: {}
  # libssh2:
  #   brew: {}
  # openssl@3:
  #   brew:
  #     link: false
  # xz:
  #   brew: {}
# cli utils
  grep:
    brew: {}
  nano:
    brew: {}
  watch:
    brew: {}
  gawk:
    brew: {}
  # GNU find, xargs, locate
  findutils:
    optional: true
    checkBrew: true
    brew: {}
  iterm2:
    optional: true
    brew:
      cask: true
  iterm-cli:
    artifact:
      url: https://iterm2.com/shell_integration/zsh
      target: ~/.iterm2_shell_integration.zsh
# rust cli utils
  bat:
    brew: {}
  eza:
    brew: {}
  fzf:
    brew: {}
toolDeps:
  # - iterm2
  - iterm-cli
  - menlo-font
  - chezmoi
  - bash
  - zsh
  - git
  - zinit
  - nano
  - grep
  - watch
  - bat
  - eza
  - fzf
  # - gnupg
