tools:
  cask:
    brew: {}
# version control
  git:
    brew: {}
  # subversion:
  #   brew: {}
# shell
  bash:
    brew: {}
  bash-completion:
    optional: true
    checkBrew: true
    brew: {}
  coreutils:
    checkBrew: true
    brew: {}
  zsh:
    brew: {}
  zsh-completions:
    optional: true
    checkBrew: true
    brew: {}
  zinit:
    optional: true
    git:
      url: https://github.com/zdharma-continuum/zinit.git
      target: "local/share"
# runtime deps
  # gcc:
  #   brew: {}
  # glib:
  #   brew: {}
  # gobject-introspection:
  #   brew: {}
  # libxml2:
  #   brew: {}
  # libxmlsec1:
  #   brew: {}
  # readline:
  #   brew: {}
  # sqlite3:
  #   brew: {}
  # zlib:
  #   brew: {}
  # tcl-tk:
  #   brew: {}
  # https://nghttp2.org/
  # nghttp2:
  #   brew: {}
# media
  # webp:
  #   brew: {}
  # jpeg-xl:
  #   brew: {}
  # libavif:
  #   brew: {}
  # aom:
  #   brew: {}
  # gd:
  #   brew: {}
  # gdk-pixbuf:
  #   brew: {}
  # netpbm:
  #   brew: {}
# fonts
  # fontconfig:
  #   brew: {}
  # harfbuzz:
  #   brew: {}
  # pango:
  #   brew: {}
# svg
  # cairo:
  #   brew: {}
  # librsvg:
  #   brew: {}
# viz
  graphviz:
    optional: true
    brew: {}
# crypto
  gnupg:
    checkCommand: gpg
    brew: {}
  # gnutls:
  #   brew: {}
  # krb5:
  #   brew: {}
  # libssh:
  #   brew: {}
  # libssh2:
  #   brew: {}
  # openssl@3:
  #   brew:
  #     link: false
  # xz:
  #   brew: {}
# cli utils
  grep:
    brew: {}
  nano:
    brew: {}
  watch:
    brew: {}
  gawk:
    brew: {}
  # GNU find, xargs, locate
  findutils:
    optional: true
    checkBrew: true
    brew: {}
  iterm2:
    checkBrew: true
    brew:
      cask: true
# rust cli utils
  bat:
    brew: {}
  eza:
    brew:
      tap: test
  fzf:
    brew: {}
      # version: "1.1"
toolDeps:
  - iterm2
  - bash
  - zsh
  - git
  - nano
  - grep
  - watch
  - bat
  - eza
  - fzf
  # - gnupg
