tools:
  pass:
    brew: true
  pass-otp:
    checkBrew: true
    brew: true
  bitwarden-cli:
    optional: true
    checkCommand: bw
    brew: true
  bitwarden:
    optional: true
    brew:
      cask: true
toolDeps:
  - pass
  - pass-otp
  - bitwarden-cli
  - bitwarden
