tools:
  pass:
    brew: {}
  pass-otp:
    checkBrew: true
    brew: {}
  bitwarden-cli:
    optional: true
    checkCommand: bw
    brew: {}
  bitwarden:
    optional: true
    brew:
      cask: true
